// _backup_react/views/CountrySelect.tsx
import React from 'react';
import { ViewState } from '../types';

interface CountrySelectProps {
  onSelect: () => void;
}

export const CountrySelect: React.FC<CountrySelectProps> = ({ onSelect }) => {
  const countries = [
    { name: 'Türkiye', flag: 'https://flagcdn.com/w320/tr.png' },
    { name: 'Almanya', flag: 'https://flagcdn.com/w320/de.png' },
    { name: 'Fransa', flag: 'https://flagcdn.com/w320/fr.png' },
    { name: 'Birleşik Krallık', flag: 'https://flagcdn.com/w320/gb.png' },
    { name: 'İspanya', flag: 'https://flagcdn.com/w320/es.png' },
    { name: 'İtalya', flag: 'https://flagcdn.com/w320/it.png' },
    { name: 'Hollanda', flag: 'https://flagcdn.com/w320/nl.png' },
    { name: 'Kanada', flag: 'https://flagcdn.com/w320/ca.png' },
    { name: 'ABD', flag: 'https://flagcdn.com/w320/us.png' },
    { name: 'Avustralya', flag: 'https://flagcdn.com/w320/au.png' },
  ];

  return (
    <div class="min-h-screen w-full bg-white">
      {/* Header */}
      <header class="flex items-center justify-between border-b border-slate-100 px-8 py-4">
        <div class="flex items-center gap-2 text-primary">
            <span className="material-symbols-outlined fill text-3xl">receipt</span>
          <h1 class="text-xl font-bold text-slate-900">Fatura Uygulaması</h1>
        </div>
        <button className="rounded-lg bg-primary px-6 py-2 text-sm font-bold text-white">Giriş Yap</button>
      </header>

      {/* Main Content */}
      <main class="container mx-auto mt-10 max-w-5xl px-4">
        <div class="mb-12 text-center">
          <h2 class="mb-2 text-4xl font-black text-slate-900">İşlem Yapılacak Ülkeyi Seçiniz</h2>
          <p class="text-slate-500">Oluşturulacak fatura, seçtiğiniz ülkenin vergi ve format kurallarına uygun olacaktır.</p>
        </div>

        <div class="mb-8">
          <p class="mb-2 font-medium text-slate-900">Adım 1/3: Ülke Seçimi</p>
          <div class="h-2 w-full rounded-full bg-slate-100">
            <div class="h-2 w-1/3 rounded-full bg-primary"></div>
          </div>
        </div>

        <div class="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
          {countries.map((country) => (
            <button
              key={country.name}
              onClick={onSelect}
              class="group flex flex-col items-center gap-3 rounded-xl p-2 transition-all hover:-translate-y-1 hover:bg-slate-50"
            >
              <div
                class="aspect-square w-full rounded-xl bg-cover bg-center shadow-sm transition-shadow group-hover:shadow-md"
                style={{ backgroundImage: `url(${country.flag})` }}
              ></div>
              <span class="font-medium text-slate-800">{country.name}</span>
            </button>
          ))}
        </div>
      </main>
      
      <footer class="mt-20 border-t border-slate-100 py-10 text-center text-sm text-slate-500">
          <div class="mb-4 flex justify-center gap-6">
              <a href="#" class="hover:text-slate-800">Gizlilik Politikası</a>
              <a href="#" class="hover:text-slate-800">Kullanım Koşulları</a>
              <a href="#" class="hover:text-slate-800">Yardım</a>
          </div>
          <p>© Fatura Uygulaması 2024</p>
      </footer>
    </div>
  );
};

// src/app/features/country-select/country-select.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { CountryService } from '../../core/services/country.service';
import { Country } from '../../core/models/country.model';

@Component({
    selector: 'app-country-select',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './country-select.component.html',
    styleUrl: './country-select.component.css'
})
export class CountrySelectComponent {
    private router = inject(Router);
    private countryService = inject(CountryService);

    countries: Country[] = this.countryService.getAllCountries();

    selectCountry(country: Country) {
        this.countryService.selectCountry(country);
        console.log('Seçilen ülke:', country.name, '- Vergi:', country.taxes.find(t => t.isDefault)?.name, country.taxes.find(t => t.isDefault)?.rate + '%');
        this.router.navigate(['/create-invoice']);
    }

    goToLogin() {
        this.router.navigate(['/login']);
    }

    getDefaultTax(country: Country) {
        return country.taxes.find(t => t.isDefault) || country.taxes[0];
    }
}

<div class="min-h-screen bg-background-light flex flex-col">
    <!-- Header -->
    <header class="flex items-center justify-between px-8 py-6 bg-white border-b border-slate-200">
        <div class="flex items-center gap-2 text-primary">
            <span class="material-symbols-outlined text-3xl">receipt_long</span>
            <span class="text-xl font-black tracking-tight">Fatura Uygulaması</span>
        </div>
        <nav class="flex gap-6 text-sm font-medium text-slate-600">
            <!-- <a href="#" class="hover:text-primary">Ana Sayfa</a>
            <a href="#" class="hover:text-primary">Faturalar</a>
            <a href="#" class="hover:text-primary">Yardım</a> -->
        </nav>
        <div class="flex items-center gap-4">
            <button (click)="goToLogin()"
                class="bg-primary text-white px-6 py-2.5 rounded-lg font-bold hover:bg-blue-700 transition-colors">
                Giriş Yap
            </button>
            <button class="w-10 h-10 rounded-full bg-orange-100 flex items-center justify-center text-orange-600">
                <span class="material-symbols-outlined">location_on</span>
            </button>
        </div>
    </header>

    <!-- Content -->
    <main class="flex-1 flex flex-col items-center justify-center p-8">
        <div class="text-center mb-12">
            <h1 class="text-4xl font-black text-slate-900 mb-4">İşlem Yapılacak Ülkeyi Seçiniz</h1>
            <p class="text-slate-500 text-lg">Oluşturulacak fatura, seçtiğiniz ülkenin vergi ve format kurallarına uygun
                olacaktır.</p>
        </div>

        <div class="w-full max-w-6xl">
            <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6">
                <button *ngFor="let country of countries" (click)="selectCountry(country)"
                    class="group flex flex-col items-center p-6 bg-white rounded-2xl border border-slate-200 hover:border-primary hover:shadow-lg hover:-translate-y-1 transition-all duration-300">
                    <div
                        class="w-16 h-16 mb-3 flex items-center justify-center text-5xl shadow-sm rounded-full bg-slate-50 group-hover:scale-110 transition-transform">
                        {{ country.flag }}
                    </div>
                    <span class="font-bold text-slate-700 group-hover:text-primary text-center">{{ country.name }}</span>
                    
                    <!-- Vergi ve Para Birimi Bilgisi -->
                    <div class="mt-3 pt-3 border-t border-slate-100 w-full text-center space-y-1">
                        <div class="flex items-center justify-center gap-1 text-xs text-slate-500">
                            <span class="material-symbols-outlined text-sm">payments</span>
                            <span class="font-medium">{{ country.currency.code }}</span>
                            <span class="text-slate-400">({{ country.currency.symbol }})</span>
                        </div>
                        <div class="flex items-center justify-center gap-1 text-xs text-slate-500">
                            <span class="material-symbols-outlined text-sm">percent</span>
                            <span>{{ getDefaultTax(country).name }}</span>
                            <span class="font-semibold text-primary">%{{ getDefaultTax(country).rate }}</span>
                        </div>
                    </div>
                </button>
            </div>
        </div>
    </main>

    <!-- Footer -->
    <footer class="py-8 text-center text-sm text-slate-500 border-t border-slate-200 bg-white">
        <div class="flex justify-center gap-6 mb-4">
            <a href="#" class="hover:text-slate-900">Gizlilik Politikası</a>
            <a href="#" class="hover:text-slate-900">Kullanım Koşulları</a>
            <a href="#" class="hover:text-slate-900">Yardım</a>
        </div>
        <p>© Fatura Uygulaması 2024</p>
    </footer>
</div>
