// _backup_react/views/CreateInvoice.tsx
import React from 'react';

export const CreateInvoice: React.FC = () => {
  return (
    <div class="p-8">
      <h1 class="mb-8 text-4xl font-black text-slate-900">Yeni Fatura Oluştur</h1>

      <div class="grid gap-8 lg:grid-cols-2">
        {/* Left Column: Form Inputs */}
        <div class="flex flex-col gap-6">
          {/* Invoice Info */}
          <div class="rounded-xl bg-white p-6 shadow-sm">
            <h2 class="mb-4 border-b border-slate-200 pb-4 text-xl font-bold text-slate-900">Fatura Bilgileri</h2>
            <div class="grid gap-4 sm:grid-cols-2">
              <div>
                <label class="mb-2 block text-sm font-medium text-slate-900">Fatura Tipi</label>
                <select class="w-full rounded-lg border-slate-300 py-3 focus:border-primary focus:ring-primary">
                  <option>Satış</option>
                  <option>İade</option>
                </select>
              </div>
              <div>
                <label class="mb-2 block text-sm font-medium text-slate-900">Fatura Senaryosu</label>
                <select class="w-full rounded-lg border-slate-300 py-3 focus:border-primary focus:ring-primary">
                  <option>Temel Fatura</option>
                  <option>Ticari Fatura</option>
                </select>
              </div>
              <div>
                <label class="mb-2 block text-sm font-medium text-slate-900">Fatura Tarihi</label>
                <input type="date" defaultValue="2024-05-24" class="w-full rounded-lg border-slate-300 py-3 focus:border-primary focus:ring-primary" />
              </div>
              <div>
                <label class="mb-2 block text-sm font-medium text-slate-900">Fatura Saati</label>
                <input type="time" defaultValue="14:30" class="w-full rounded-lg border-slate-300 py-3 focus:border-primary focus:ring-primary" />
              </div>
            </div>
          </div>

          {/* Customer Info */}
          <div class="rounded-xl bg-white p-6 shadow-sm">
            <h2 class="mb-4 border-b border-slate-200 pb-4 text-xl font-bold text-slate-900">Müşteri Bilgileri</h2>
            <div class="grid gap-4 sm:grid-cols-2">
              <div class="sm:col-span-2">
                <label class="mb-2 block text-sm font-medium text-slate-900">Müşteri Adı / Ünvanı</label>
                <input type="text" placeholder="Müşteri adını girin" class="w-full rounded-lg border-slate-300 py-3 focus:border-primary focus:ring-primary" />
              </div>
              <div>
                <label class="mb-2 block text-sm font-medium text-slate-900">Vergi Numarası</label>
                <input type="text" placeholder="Vergi numarasını girin" class="w-full rounded-lg border-slate-300 py-3 focus:border-primary focus:ring-primary" />
              </div>
              <div>
                <label class="mb-2 block text-sm font-medium text-slate-900">Adres</label>
                <input type="text" placeholder="Müşteri adresini girin" class="w-full rounded-lg border-slate-300 py-3 focus:border-primary focus:ring-primary" />
              </div>
            </div>
          </div>

           {/* Tax Settings */}
           <div class="rounded-xl bg-white p-6 shadow-sm">
             <h2 class="mb-4 border-b border-slate-200 pb-4 text-xl font-bold text-slate-900">Vergi Ayarları (Türkiye)</h2>
             <div class="space-y-4">
               <div class="grid grid-cols-12 gap-2 text-sm font-semibold text-slate-500">
                 <div class="col-span-6">Vergi Adı</div>
                 <div class="col-span-3 text-center">Oran (%)</div>
                 <div class="col-span-2 text-center">Uygula</div>
                 <div class="col-span-1"></div>
               </div>
               <div class="grid grid-cols-12 items-center gap-2">
                 <input type="text" defaultValue="KDV" class="col-span-6 h-10 rounded-lg border-slate-300 text-sm" />
                 <input type="number" defaultValue="20" class="col-span-3 h-10 rounded-lg border-slate-300 text-center text-sm" />
                 <div class="col-span-2 flex justify-center"><input type="checkbox" checked class="h-5 w-5 rounded border-slate-300 text-primary focus:ring-primary" /></div>
                 <button class="col-span-1 text-slate-400 hover:text-red-500 flex justify-center"><span className="material-symbols-outlined text-[18px]">delete</span></button>
               </div>
                <div class="grid grid-cols-12 items-center gap-2">
                 <input type="text" defaultValue="ÖİV" class="col-span-6 h-10 rounded-lg border-slate-300 text-sm" />
                 <input type="number" defaultValue="10" class="col-span-3 h-10 rounded-lg border-slate-300 text-center text-sm" />
                 <div class="col-span-2 flex justify-center"><input type="checkbox" class="h-5 w-5 rounded border-slate-300 text-primary focus:ring-primary" /></div>
                 <button class="col-span-1 text-slate-400 hover:text-red-500 flex justify-center"><span className="material-symbols-outlined text-[18px]">delete</span></button>
               </div>
               <button class="flex items-center gap-2 text-sm font-bold text-primary hover:underline">
                 <span className="material-symbols-outlined text-[18px]">add_circle</span>
                 Yeni Vergi Ekle
               </button>
             </div>
           </div>

           {/* Line Items */}
           <div class="rounded-xl bg-white p-6 shadow-sm">
             <h2 class="mb-4 border-b border-slate-200 pb-4 text-xl font-bold text-slate-900">Fatura Kalemleri</h2>
              <div class="space-y-4">
                 <div class="hidden grid-cols-12 gap-2 px-2 text-sm font-semibold text-slate-500 md:grid">
                   <div class="col-span-3">Açıklama</div>
                   <div class="col-span-1 text-center">Miktar</div>
                   <div class="col-span-2 text-right">Birim Fiyat</div>
                   <div class="col-span-3">Vergiler</div>
                   <div class="col-span-2 text-right">Toplam</div>
                   <div class="col-span-1"></div>
                 </div>
                 {/* Item 1 */}
                 <div class="grid grid-cols-1 gap-2 border-b border-slate-100 pb-4 md:grid-cols-12 md:items-center md:border-none md:pb-0">
                   <input type="text" defaultValue="Web Tasarım Hizmeti" class="h-10 rounded-lg border-slate-300 text-sm md:col-span-3" placeholder="Ürün" />
                   <input type="number" defaultValue="1" class="h-10 rounded-lg border-slate-300 text-center text-sm md:col-span-1" />
                   <input type="text" defaultValue="150.00" class="h-10 rounded-lg border-slate-300 text-right text-sm md:col-span-2" />
                   <div class="md:col-span-3">
                     <select multiple class="h-10 w-full rounded-lg border-slate-300 text-sm">
                       <option selected>KDV %20</option>
                       <option>ÖİV %10</option>
                     </select>
                   </div>
                   <p class="text-right text-sm font-medium md:col-span-2">₺180.00</p>
                   <button class="flex justify-center text-slate-400 hover:text-red-500 md:col-span-1"><span className="material-symbols-outlined text-[18px]">delete</span></button>
                 </div>
                 {/* Item 2 */}
                  <div class="grid grid-cols-1 gap-2 border-b border-slate-100 pb-4 md:grid-cols-12 md:items-center md:border-none md:pb-0">
                   <input type="text" defaultValue="Logo Tasarımı" class="h-10 rounded-lg border-slate-300 text-sm md:col-span-3" placeholder="Ürün" />
                   <input type="number" defaultValue="2" class="h-10 rounded-lg border-slate-300 text-center text-sm md:col-span-1" />
                   <input type="text" defaultValue="75.00" class="h-10 rounded-lg border-slate-300 text-right text-sm md:col-span-2" />
                   <div class="md:col-span-3">
                     <select multiple class="h-10 w-full rounded-lg border-slate-300 text-sm">
                       <option selected>KDV %20</option>
                       <option selected>ÖİV %10</option>
                     </select>
                   </div>
                   <p class="text-right text-sm font-medium md:col-span-2">₺195.00</p>
                   <button class="flex justify-center text-slate-400 hover:text-red-500 md:col-span-1"><span className="material-symbols-outlined text-[18px]">delete</span></button>
                 </div>
                 <button class="flex items-center gap-2 text-sm font-bold text-primary hover:underline">
                    <span className="material-symbols-outlined text-[18px]">add_circle</span>
                   Yeni Kalem Ekle
                 </button>
              </div>
              
              <div class="mt-6 flex flex-col justify-end gap-3 sm:flex-row">
                <button class="h-11 rounded-lg bg-slate-200 px-6 text-sm font-bold text-slate-900 hover:bg-slate-300">Taslak Olarak Kaydet</button>
                <button class="h-11 rounded-lg bg-primary px-6 text-sm font-bold text-white hover:bg-blue-700">Faturayı Oluştur</button>
              </div>
           </div>
        </div>

        {/* Right Column: Preview */}
        <div class="h-fit rounded-xl border border-slate-200 bg-white p-8 shadow-lg">
          <div class="mb-8 flex items-start justify-between border-b border-slate-200 pb-8">
            <div>
              <h3 class="text-xl font-bold text-slate-800">Şirket Adınız</h3>
              <p class="text-sm text-slate-500">Vergi Dairesi, Vergi No: 1234567890</p>
              <p class="text-sm text-slate-500">Adresiniz, Şehir, Ülke</p>
            </div>
            <h1 class="text-3xl font-extrabold tracking-wider text-slate-800">FATURA</h1>
          </div>

          <div class="mb-6 flex justify-between">
            <div>
              <p class="font-semibold text-slate-700">Alıcı:</p>
              <p class="text-slate-600">Müşteri Adı / Ünvanı</p>
              <p class="text-slate-600">Müşteri Adresi</p>
              <p class="text-slate-600">Vergi No: 9876543210</p>
            </div>
            <div class="text-right">
              <p><span class="font-semibold text-slate-700">Fatura No:</span> INV-00123</p>
              <p><span class="font-semibold text-slate-700">Tarih:</span> 24/05/2024</p>
              <p><span class="font-semibold text-slate-700">Son Ödeme:</span> 08/06/2024</p>
            </div>
          </div>

          <table class="mb-6 w-full text-left">
            <thead class="border-b-2 border-slate-300">
              <tr>
                <th class="py-2 pr-2 font-semibold text-slate-700">Açıklama</th>
                <th class="px-2 py-2 text-center font-semibold text-slate-700">Miktar</th>
                <th class="px-2 py-2 text-right font-semibold text-slate-700">Birim Fiyat</th>
                <th class="pl-2 py-2 text-right font-semibold text-slate-700">Toplam</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-200">
              <tr>
                <td class="py-3 pr-2">Web Tasarım Hizmeti</td>
                <td class="px-2 py-3 text-center">1</td>
                <td class="px-2 py-3 text-right">₺150.00</td>
                <td class="pl-2 py-3 text-right">₺180.00</td>
              </tr>
              <tr>
                <td class="py-3 pr-2">Logo Tasarımı</td>
                <td class="px-2 py-3 text-center">2</td>
                <td class="px-2 py-3 text-right">₺75.00</td>
                <td class="pl-2 py-3 text-right">₺195.00</td>
              </tr>
            </tbody>
          </table>

          <div class="flex justify-end">
            <div class="w-full max-w-xs space-y-2 text-sm">
              <div class="flex justify-between">
                <span class="text-slate-600">Ara Toplam:</span>
                <span class="font-medium text-slate-800">₺300.00</span>
              </div>
              <div class="flex justify-between">
                <span class="text-slate-600">KDV (%20):</span>
                <span class="font-medium text-slate-800">₺60.00</span>
              </div>
              <div class="flex justify-between">
                <span class="text-slate-600">ÖİV (%10):</span>
                <span class="font-medium text-slate-800">₺15.00</span>
              </div>
              <div class="mt-2 flex justify-between border-t-2 border-slate-300 pt-2">
                <span class="text-lg font-bold text-slate-800">Genel Toplam:</span>
                <span class="text-lg font-bold text-slate-800">₺375.00</span>
              </div>
            </div>
          </div>

          <div class="mt-8 border-t border-slate-200 pt-4 text-center">
            <p class="text-xs text-slate-500">Ödemeleriniz için teşekkür ederiz. Sorularınız için bizimle iletişime geçebilirsiniz.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

// src/app/features/create-invoice/create-invoice.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ButtonComponent } from '../../shared/components/button/button.component';
import { InputComponent } from '../../shared/components/input/input.component';
import { CardComponent } from '../../shared/components/card/card.component';

@Component({
    selector: 'app-create-invoice',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, ButtonComponent, InputComponent],
    templateUrl: './create-invoice.component.html',
    styleUrl: './create-invoice.component.css'
})
export class CreateInvoiceComponent {
    invoiceForm: FormGroup;

    constructor(private fb: FormBuilder, private router: Router) {
        this.invoiceForm = this.fb.group({
            date: [new Date().toISOString().split('T')[0], Validators.required],
            time: ['14:30'],
            customerName: ['', Validators.required],
            taxId: [''],
            address: [''],
            items: this.fb.array([])
        });

        // Add initial item
        this.addItem();
    }

    get items() {
        return this.invoiceForm.get('items') as FormArray;
    }

    addItem() {
        const itemForm = this.fb.group({
            description: ['', Validators.required],
            quantity: [1, [Validators.required, Validators.min(1)]],
            unitPrice: [0, [Validators.required, Validators.min(0)]]
        });
        this.items.push(itemForm);
    }

    removeItem(index: number) {
        this.items.removeAt(index);
    }

    calculateSubtotal(): number {
        return this.items.controls.reduce((acc, item) => {
            const quantity = item.get('quantity')?.value || 0;
            const unitPrice = item.get('unitPrice')?.value || 0;
            return acc + (quantity * unitPrice);
        }, 0);
    }

    calculateTax(): number {
        return this.calculateSubtotal() * 0.20; // 20% KDV
    }

    calculateTotal(): number {
        return this.calculateSubtotal() + this.calculateTax();
    }

    goBack() {
        this.router.navigate(['/']);
    }

    saveInvoice() {
        if (this.invoiceForm.valid) {
            console.log('Invoice Data:', this.invoiceForm.value);
            // Save logic here
            alert('Fatura başarıyla oluşturuldu!');
            this.router.navigate(['/invoices']);
        } else {
            alert('Lütfen tüm zorunlu alanları doldurun.');
        }
    }
}

<div class="flex h-screen overflow-hidden bg-slate-50">
    <!-- Left Side: Form -->
    <div class="w-1/2 h-full overflow-y-auto border-r border-slate-200 bg-white p-8">
        <div class="max-w-2xl mx-auto space-y-8">
            <div class="flex items-center justify-between">
                <h1 class="text-2xl font-bold text-slate-900">Yeni Fatura Oluştur</h1>
                <app-button variant="ghost" icon="arrow_back" (click)="goBack()">Geri Dön</app-button>
            </div>

            <!-- Fatura Bilgileri -->
            <section class="space-y-4">
                <h2 class="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2">Fatura Bilgileri</h2>
                <div class="grid grid-cols-2 gap-4">
                    <app-input label="Fatura Tipi" placeholder="Satış" [disabled]="true"></app-input>
                    <app-input label="Fatura Senaryosu" placeholder="Temel Fatura" [disabled]="true"></app-input>
                    <app-input label="Fatura Tarihi" type="date"
                        [formControl]="$any(invoiceForm.get('date'))"></app-input>
                    <app-input label="Fatura Saati" type="time"
                        [formControl]="$any(invoiceForm.get('time'))"></app-input>
                </div>
            </section>

            <!-- Müşteri Bilgileri -->
            <section class="space-y-4">
                <h2 class="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2">Müşteri Bilgileri</h2>
                <app-input label="Müşteri Adı / Ünvanı" placeholder="Müşteri adını girin"
                    [formControl]="$any(invoiceForm.get('customerName'))"></app-input>
                <div class="grid grid-cols-2 gap-4">
                    <app-input label="Vergi Numarası" placeholder="Vergi numarasını girin"
                        [formControl]="$any(invoiceForm.get('taxId'))"></app-input>
                    <app-input label="Adres" placeholder="Müşteri adresini girin"
                        [formControl]="$any(invoiceForm.get('address'))"></app-input>
                </div>
            </section>

            <!-- Vergi Ayarları -->
            <section class="space-y-4">
                <h2 class="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2">Vergi Ayarları (Türkiye)
                </h2>
                <div class="flex items-center gap-4 bg-slate-50 p-4 rounded-lg border border-slate-200">
                    <div class="flex-1">
                        <label class="block text-sm font-medium text-slate-700 mb-1">Vergi Adı</label>
                        <input type="text" value="KDV" disabled
                            class="w-full bg-white rounded border-slate-300 text-sm">
                    </div>
                    <div class="w-24">
                        <label class="block text-sm font-medium text-slate-700 mb-1">Oran (%)</label>
                        <input type="number" value="20" disabled
                            class="w-full bg-white rounded border-slate-300 text-sm">
                    </div>
                    <div class="flex items-center pt-6">
                        <input type="checkbox" checked disabled class="h-5 w-5 rounded border-slate-300 text-primary">
                    </div>
                </div>
            </section>

            <!-- Fatura Kalemleri -->
            <section class="space-y-4">
                <h2 class="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2">Fatura Kalemleri</h2>

                <div class="space-y-4">
                    <div *ngFor="let item of items.controls; let i = index" [formGroup]="$any(item)"
                        class="flex gap-3 items-start p-4 bg-slate-50 rounded-lg border border-slate-200 group">
                        <div class="flex-1">
                            <label class="block text-xs font-medium text-slate-500 mb-1">Açıklama</label>
                            <input type="text" formControlName="description"
                                class="w-full rounded border-slate-300 text-sm" placeholder="Ürün/Hizmet adı">
                        </div>
                        <div class="w-20">
                            <label class="block text-xs font-medium text-slate-500 mb-1">Miktar</label>
                            <input type="number" formControlName="quantity"
                                class="w-full rounded border-slate-300 text-sm">
                        </div>
                        <div class="w-24">
                            <label class="block text-xs font-medium text-slate-500 mb-1">Birim Fiyat</label>
                            <input type="number" formControlName="unitPrice"
                                class="w-full rounded border-slate-300 text-sm">
                        </div>
                        <div class="w-24 pt-6 text-right font-medium text-slate-900">
                            {{ (item.get('quantity')?.value * item.get('unitPrice')?.value) |
                            currency:'TRY':'symbol-narrow':'1.2-2' }}
                        </div>
                        <button (click)="removeItem(i)" class="mt-6 text-slate-400 hover:text-red-600">
                            <span class="material-symbols-outlined">delete</span>
                        </button>
                    </div>
                </div>

                <button (click)="addItem()"
                    class="flex items-center gap-2 text-primary font-bold hover:text-blue-700 text-sm">
                    <span class="material-symbols-outlined text-lg">add_circle</span>
                    Yeni Kalem Ekle
                </button>
            </section>

            <!-- Actions -->
            <div class="flex items-center justify-end gap-4 pt-8 border-t border-slate-200">
                <app-button variant="secondary">Taslak Olarak Kaydet</app-button>
                <app-button variant="primary" (click)="saveInvoice()">Faturayı Oluştur</app-button>
            </div>
        </div>
    </div>

    <!-- Right Side: Preview -->
    <div class="w-1/2 h-full bg-slate-100 p-8 overflow-y-auto flex justify-center items-start">
        <!-- A4 Paper -->
        <div
            class="w-full max-w-[210mm] aspect-[210/297] bg-white shadow-2xl p-[10mm] md:p-[20mm] text-slate-900 text-sm relative">
            <!-- Header -->
            <div class="flex justify-between items-start mb-12">
                <div>
                    <h2 class="text-2xl font-bold text-slate-900 mb-2">Şirket Adınız</h2>
                    <p class="text-slate-500 text-xs">Vergi Dairesi: Zincirlikuyu</p>
                    <p class="text-slate-500 text-xs">Vergi No: 1234567890</p>
                    <p class="text-slate-500 text-xs">İstanbul, Türkiye</p>
                </div>
                <div class="text-right">
                    <h1 class="text-4xl font-black text-slate-900 tracking-widest mb-4">FATURA</h1>
                    <div class="text-xs space-y-1">
                        <p><span class="font-bold text-slate-700">Fatura No:</span> INV-00123</p>
                        <p><span class="font-bold text-slate-700">Tarih:</span> {{ invoiceForm.get('date')?.value |
                            date:'dd/MM/yyyy' }}</p>
                    </div>
                </div>
            </div>

            <!-- Client Info -->
            <div class="mb-12 border-b border-slate-200 pb-8">
                <h3 class="font-bold text-slate-900 mb-2">Sayın:</h3>
                <p class="text-lg font-medium">{{ invoiceForm.get('customerName')?.value || 'Müşteri Adı' }}</p>
                <p class="text-slate-500">{{ invoiceForm.get('address')?.value || 'Adres bilgisi girilmedi' }}</p>
                <p class="text-slate-500 mt-1" *ngIf="invoiceForm.get('taxId')?.value">VN: {{
                    invoiceForm.get('taxId')?.value }}</p>
            </div>

            <!-- Items Table -->
            <table class="w-full mb-8">
                <thead>
                    <tr class="border-b-2 border-slate-900 text-xs uppercase tracking-wider">
                        <th class="text-left py-3">Açıklama</th>
                        <th class="text-right py-3 w-20">Miktar</th>
                        <th class="text-right py-3 w-32">Birim Fiyat</th>
                        <th class="text-right py-3 w-32">Toplam</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-200">
                    <tr *ngFor="let item of items.controls">
                        <td class="py-4">{{ item.get('description')?.value }}</td>
                        <td class="text-right py-4">{{ item.get('quantity')?.value }}</td>
                        <td class="text-right py-4">{{ item.get('unitPrice')?.value |
                            currency:'TRY':'symbol-narrow':'1.2-2' }}</td>
                        <td class="text-right py-4 font-medium">{{ (item.get('quantity')?.value *
                            item.get('unitPrice')?.value) | currency:'TRY':'symbol-narrow':'1.2-2' }}</td>
                    </tr>
                </tbody>
            </table>

            <!-- Totals -->
            <div class="flex justify-end">
                <div class="w-64 space-y-3">
                    <div class="flex justify-between text-slate-600">
                        <span>Ara Toplam:</span>
                        <span>{{ calculateSubtotal() | currency:'TRY':'symbol-narrow':'1.2-2' }}</span>
                    </div>
                    <div class="flex justify-between text-slate-600">
                        <span>KDV (%20):</span>
                        <span>{{ calculateTax() | currency:'TRY':'symbol-narrow':'1.2-2' }}</span>
                    </div>
                    <div class="flex justify-between text-lg font-bold text-slate-900 border-t border-slate-900 pt-3">
                        <span>Genel Toplam:</span>
                        <span>{{ calculateTotal() | currency:'TRY':'symbol-narrow':'1.2-2' }}</span>
                    </div>
                </div>
            </div>

            <!-- Footer Note -->
            <div class="absolute bottom-[20mm] left-[20mm] right-[20mm] text-center text-xs text-slate-400">
                Ödemeleriniz için teşekkür ederiz. Sorularınız için bizimle iletişime geçebilirsiniz.
            </div>
        </div>
    </div>
</div>
