// src/app/shared/components/card/card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-card',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './card.component.html',
    styleUrl: './card.component.css'
})
export class CardComponent {
    @Input() title?: string;
    @Input() className = '';
}

<div class="rounded-xl bg-white p-6 shadow-sm" [ngClass]="className">
    <div *ngIf="title" class="mb-4 flex items-center justify-between border-b border-slate-200 pb-4">
        <h2 class="text-xl font-bold text-slate-900">{{ title }}</h2>
        <div class="card-actions">
            <ng-content select="[actions]"></ng-content>
        </div>
    </div>
    <ng-content></ng-content>
</div>

// _backup_react/components/ui/Card.tsx
import React, { ReactNode } from 'react';

interface CardProps {
    title?: string;
    children: ReactNode;
    className?: string;
    action?: ReactNode;
}

export const Card: React.FC<CardProps> = ({ title, children, className = '', action }) => {
    return (
        <div className={`rounded-xl bg-white p-6 shadow-sm ${className}`}>
            {(title || action) && (
                <div className="mb-4 flex items-center justify-between border-b border-slate-200 pb-4">
                    {title && <h2 className="text-xl font-bold text-slate-900">{title}</h2>}
                    {action && <div>{action}</div>}
                </div>
            )}
            {children}
        </div>
    );
};
