// src/app/shared/components/input/input.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR, FormsModule } from '@angular/forms';

@Component({
    selector: 'app-input',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './input.component.html',
    styleUrl: './input.component.css',
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => InputComponent),
            multi: true
        }
    ]
})
export class InputComponent implements ControlValueAccessor {
    @Input() label?: string;
    @Input() type = 'text';
    @Input() placeholder = '';
    @Input() error?: string;
    @Input() icon?: string;
    @Input() id = Math.random().toString(36).substr(2, 9);
    @Input() disabled: boolean = false;

    value: string = '';

    onChange: any = () => { };
    onTouch: any = () => { };

    writeValue(value: any): void {
        this.value = value;
    }

    registerOnChange(fn: any): void {
        this.onChange = fn;
    }

    registerOnTouched(fn: any): void {
        this.onTouch = fn;
    }

    setDisabledState(isDisabled: boolean): void {
        this.disabled = isDisabled;
    }

    onInput(event: Event) {
        const value = (event.target as HTMLInputElement).value;
        this.value = value;
        this.onChange(value);
        this.onTouch();
    }
}

<div class="w-full">
    <label *ngIf="label" [for]="id" class="mb-2 block text-sm font-medium text-slate-900">
        {{ label }}
    </label>
    <div class="relative">
        <span *ngIf="icon" class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">
            {{ icon }}
        </span>
        <input [id]="id" [type]="type" [value]="value" [placeholder]="placeholder" [disabled]="disabled"
            (input)="onInput($event)" (blur)="onTouch()"
            class="w-full rounded-lg border border-slate-300 py-2.5 text-sm focus:border-primary focus:ring-1 focus:ring-primary disabled:bg-slate-100 disabled:text-slate-500"
            [ngClass]="{
        'pl-10': icon,
        'px-3': !icon,
        'border-red-500 focus:border-red-500 focus:ring-red-500': error
      }" />
    </div>
    <p *ngIf="error" class="mt-1 text-xs text-red-500">{{ error }}</p>
</div>

// _backup_react/components/ui/Input.tsx
import React, { InputHTMLAttributes } from 'react';

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
    label?: string;
    error?: string;
    icon?: string;
}

export const Input: React.FC<InputProps> = ({
    label,
    error,
    icon,
    className = '',
    id,
    ...props
}) => {
    const inputId = id || props.name || Math.random().toString(36).substr(2, 9);

    return (
        <div className={className}>
            {label && (
                <label htmlFor={inputId} className="mb-2 block text-sm font-medium text-slate-900">
                    {label}
                </label>
            )}
            <div className="relative">
                {icon && (
                    <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">
                        {icon}
                    </span>
                )}
                <input
                    id={inputId}
                    className={`w-full rounded-lg border border-slate-300 py-3 ${icon ? 'pl-10' : 'px-3'} text-sm focus:border-primary focus:ring-1 focus:ring-primary disabled:bg-slate-100 ${error ? 'border-red-500 focus:border-red-500 focus:ring-red-500' : ''}`}
                    {...props}
                />
            </div>
            {error && <p className="mt-1 text-xs text-red-500">{error}</p>}
        </div>
    );
};
